INTERNACION - Agrega test para deshacer internacion
andes/andes-test-integracion pull request #260
Opened 2020-10-07 17:42 UTC by GaboCancellieri

### Requerimiento
 
Agrega test para deshacer internacion.
### Funcionalidad desarrollada 

1. Agrega test para deshacer internacion.
2. 
3. 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-10-08 11:44 UTC, palita1991 requested changes
@GaboCancellieri revisar conflictos

2020-10-08 14:46 UTC, GaboCancellieri commented
> @GaboCancellieri revisar conflictos

@palita1991 resolvidos :)

2020-10-15 13:58 UTC, liquid36 commented on cypress/integration/apps/rup/internacion/mapa-camas/detalle-cama.spec.js
> +    });
Estaría buenmo chequear que se vea la cama desocupada y demas.

2020-10-15 13:58 UTC, liquid36 commented on cypress/integration/apps/rup/internacion/mapa-camas/detalle-cama.spec.js
> +    });
cy.getCama(cama.cama.nombre).contains('disponible')

2020-10-15 14:01 UTC, liquid36 approved these changes

2020-10-15 14:29 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2201](http://condorpiedra.andes.gob.ar:85/2201/mochawesome.html)
CYPRESS RUN: [1383](https://dashboard.cypress.io/projects/xr7gft/runs/1383/specs)
TEST START: 2020-10-15T14:28:10.781Z
TOTAL: 323
SUCCESS: 322
FAIL: 1
SKIPPED: 0

2020-10-15 14:31 UTC, liquid36 commented
Revisar el TEST que falla.

2020-10-16 12:21 UTC, liquid36 commented
USUARIO: gcancellieri  
BUILD NUMBER: [2223](http://condorpiedra.andes.gob.ar:85/2223/mochawesome.html)
CYPRESS RUN: [1405](https://dashboard.cypress.io/projects/xr7gft/runs/1405/specs)
TEST START: 2020-10-16T12:21:18.139Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-19 16:19 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2251](http://condorpiedra.andes.gob.ar:85/2251/mochawesome.html)
CYPRESS RUN: [1429](https://dashboard.cypress.io/projects/xr7gft/runs/1429/specs)
TEST START: 2020-10-19T16:19:03.383Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-19 16:53 UTC, merged