Adjuntos mobile
andes/andes-test-integracion pull request #273
Opened 2020-10-26 17:53 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-89
### Funcionalidad desarrollada 

1. test de adjuntos RUP Mobile
2. 
3. 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-10-27 13:37 UTC, liquid36 requested changes
en la carpeta "data" van las tablas maestras, todo lo demás son datos generados por los test. Y varían de test en test.

2020-10-27 13:37 UTC, liquid36 commented on data/paciente/paciente_basic.json
> +[
NEGATIVO! Los paciente tienen su seed de creación. por favor, seguir el estandar del proyecto.

2020-10-27 13:37 UTC, liquid36 commented on cypress/integration/apps/app-mobile/auth/profile.spec.js
> +        cy.get('.nologin').click();
el login se testea una vez y listo, después de puede abstraer como esta hecho en todas las otras apps.

2020-10-27 13:37 UTC, liquid36 commented on cypress/integration/apps/app-mobile/auth/profile.spec.js
> +        cy.get('.nologin').click();
PARA TODOS LOS TEST APLICA

2020-10-27 13:37 UTC, liquid36 commented on data/authUsers/authUsers_basic.json
> +    {
Para que agregan mas usuarios?

2020-10-27 13:37 UTC, liquid36 commented on data/campanias/campanias_basic.json
> +{
Crear un seed de campañas,

2020-10-27 13:37 UTC, liquid36 commented on data/nomivac/nomivac_basic.json
> +[
Crear un seed de nomivac. Y hacer varios testeos. Con y sin vacunas, distintos pacientes.

2020-10-27 13:37 UTC, liquid36 commented on data/prestaciones/prestaciones.json
> +{
Ni chance de que esto venga acá.

2020-10-29 18:11 UTC, plammel commented
Se mueve a https://github.com/andes/andes-test-integracion/pull/279

2020-10-29 18:11 UTC, closed without merging