COM: test traslado especial
andes/andes-test-integracion pull request #318
Opened 2021-02-08 17:38 UTC by plammel

### Requerimiento
https://proyectos.andes.gob.ar/browse/COM-53
 
Test para traslados especiales en derivaciones COM
### Funcionalidad desarrollada 

1. 
2. 
3. 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-02-09 15:44 UTC, sychus requested changes
Revisar please!

2021-02-09 15:44 UTC, sychus commented on cypress/integration/apps/com/com.spec.js
> +    it.only('crear derivacion traslado especial', () => {
quitar only, para q ejecuten todos.

2021-02-09 15:44 UTC, sychus commented on cypress/integration/apps/com/com.spec.js
> +        seleccionarPaciente('2504195');
crear arriba un paciente nuevo COM-6 para que no pinche porque ya va a tener asiganda una derivación

2021-02-09 16:45 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3264](http://condorpiedra.andes.gob.ar:85/3264/mochawesome.html)
CYPRESS RUN: [2380](https://dashboard.cypress.io/projects/xr7gft/runs/2380/specs)
TEST START: 2021-02-09T16:43:55.434Z
TOTAL: 355
SUCCESS: 345
FAIL: 10
SKIPPED: 0

2021-02-09 18:02 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3269](http://condorpiedra.andes.gob.ar:85/3269/mochawesome.html)
CYPRESS RUN: [2385](https://dashboard.cypress.io/projects/xr7gft/runs/2385/specs)
TEST START: 2021-02-09T18:01:50.750Z
TOTAL: 355
SUCCESS: 336
FAIL: 19
SKIPPED: 0

2021-02-10 02:34 UTC, sychus requested changes
Lo vemos juntos a ver q está pasando.

2021-02-10 02:34 UTC, sychus commented on cypress/integration/apps/com/com.spec.js
> +        cy.route('GET', '**/api/core/mpi/pacientes**').as('searchPaciente');
Ojo acá... la ruta tiene que ir a core-v2 como estaba. Hay que ver porque está llamando a la ruta vieja. Pero el test en jenkins funciona bien con la ruta v2.

2021-02-10 13:19 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3278](http://condorpiedra.andes.gob.ar:85/3278/mochawesome.html)
CYPRESS RUN: [2393](https://dashboard.cypress.io/projects/xr7gft/runs/2393/specs)
TEST START: 2021-02-10T13:09:34.599Z
TOTAL: 355
SUCCESS: 345
FAIL: 10
SKIPPED: 0

2021-02-10 13:54 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3280](http://condorpiedra.andes.gob.ar:85/3280/mochawesome.html)
CYPRESS RUN: [2395](https://dashboard.cypress.io/projects/xr7gft/runs/2395/specs)
TEST START: 2021-02-10T13:44:32.978Z
TOTAL: 7
SUCCESS: 6
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-10 18:55 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3287](http://condorpiedra.andes.gob.ar:85/3287/mochawesome.html)
CYPRESS RUN: [2402](https://dashboard.cypress.io/projects/xr7gft/runs/2402/specs)
TEST START: 2021-02-10T18:45:48.191Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-11 10:35 UTC, sychus approved these changes

2021-02-11 10:35 UTC, merged