MPI - Corrige edición de contactos en ventanilla
andes/andes-test-integracion pull request #325
Opened 2021-02-19 18:13 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-327

### Funcionalidad desarrollada 

1. Carga un numero de telefono con formato valido

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-02-19 18:26 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3389](http://condorpiedra.andes.gob.ar:85/3389/mochawesome.html)
CYPRESS RUN: [2492](https://dashboard.cypress.io/projects/xr7gft/runs/2492/specs)
TEST START: 2021-02-19T18:20:33.136Z
TOTAL: 273
SUCCESS: 260
FAIL: 4
SKIPPED: 9
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-19 19:46 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3392](http://condorpiedra.andes.gob.ar:85/3392/mochawesome.html)
CYPRESS RUN: [2495](https://dashboard.cypress.io/projects/xr7gft/runs/2495/specs)
TEST START: 2021-02-19T19:45:30.090Z
TOTAL: 344
SUCCESS: 341
FAIL: -6
SKIPPED: 9

2021-02-22 17:40 UTC, palita1991 requested changes
Revisar que estan varios test con .skip

2021-02-26 13:17 UTC, palita1991 approved these changes

2021-03-01 16:23 UTC, merged