feat(MPI-355) Se agregaron test para lugar de nacimiento
andes/andes-test-integracion pull request #371
Opened 2021-06-24 16:01 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-355

### Funcionalidad desarrollada
1. Se crearon distintos test para verificar el lugar de nacimiento del paciente.

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

2021-06-24 16:18 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4417](http://condorpiedra.andes.gob.ar:85/4417/mochawesome.html)
CYPRESS RUN: [3434](https://dashboard.cypress.io/projects/xr7gft/runs/3434/specs)
TEST START: 2021-06-24T16:17:46.136Z
TOTAL: 402
SUCCESS: 397
FAIL: 4
SKIPPED: 1

2021-06-25 15:24 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4422](http://condorpiedra.andes.gob.ar:85/4422/mochawesome.html)
CYPRESS RUN: [3439](https://dashboard.cypress.io/projects/xr7gft/runs/3439/specs)
TEST START: 2021-06-25T15:23:50.095Z
TOTAL: 393
SUCCESS: 391
FAIL: 1
SKIPPED: 1

2021-06-25 16:07 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4425](http://condorpiedra.andes.gob.ar:85/4425/mochawesome.html)
CYPRESS RUN: [3442](https://dashboard.cypress.io/projects/xr7gft/runs/3442/specs)
TEST START: 2021-06-25T16:07:12.605Z
TOTAL: 402
SUCCESS: 399
FAIL: 2
SKIPPED: 1

2021-06-25 16:11 UTC, palita1991 requested changes
Esto se repite en todos los test, quizas podrías fijarte si es posible ponerlos en el beforeEach ya que se ejecuta siempre antes de cada uno de los test, y de esta manera no esta en cada uno de ellos
```
cy.route('GET', '**api/core-v2/mpi/pacientes**').as('getPaciente');
cy.route('GET', '**api/core-v2/mpi/pacientes/**').as('findPacienteByID');
cy.route('PATCH', '**api/core-v2/mpi/pacientes/**').as('patchPaciente');
```

2021-06-25 18:37 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4432](http://condorpiedra.andes.gob.ar:85/4432/mochawesome.html)
CYPRESS RUN: [3449](https://dashboard.cypress.io/projects/xr7gft/runs/3449/specs)
TEST START: 2021-06-25T18:37:28.895Z
TOTAL: 402
SUCCESS: 394
FAIL: 7
SKIPPED: 1

2021-07-06 11:29 UTC, liquid36 approved these changes

2021-07-06 11:36 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4497](http://condorpiedra.andes.gob.ar:85/4497/mochawesome.html)
CYPRESS RUN: [3516](https://dashboard.cypress.io/projects/xr7gft/runs/3516/specs)
TEST START: 2021-07-06T11:36:12.899Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-07-06 11:37 UTC, merged