IN -  Control anular internación
andes/andes-test-integracion pull request #480
Opened 2023-07-25 18:16 UTC by aldoEMatamala

### Requerimiento
 

### Funcionalidad desarrollada 

1. Modificada leyenda al "deshacer internación" 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2023-07-25 18:18 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9266](http://condorpiedra.andes.gob.ar:85/9266/mochawesome.html)
CYPRESS RUN: [8412](https://dashboard.cypress.io/projects/xr7gft/runs/8412/specs)
TEST START: 2023-07-25T18:18:01.308Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-16 13:56 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9436](http://condorpiedra.andes.gob.ar:85/9436/mochawesome.html)
CYPRESS RUN: [8573](https://dashboard.cypress.io/projects/xr7gft/runs/8573/specs)
TEST START: 2023-08-16T13:56:29.425Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-16 14:10 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9437](http://condorpiedra.andes.gob.ar:85/9437/mochawesome.html)
CYPRESS RUN: [8574](https://dashboard.cypress.io/projects/xr7gft/runs/8574/specs)
TEST START: 2023-08-16T14:09:17.101Z
TOTAL: 361
SUCCESS: 350
FAIL: 9
SKIPPED: 2

2023-08-16 16:15 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9447](http://condorpiedra.andes.gob.ar:85/9447/mochawesome.html)
CYPRESS RUN: [8578](https://dashboard.cypress.io/projects/xr7gft/runs/8578/specs)
TEST START: 2023-08-16T16:14:01.671Z
TOTAL: 360
SUCCESS: 348
FAIL: 10
SKIPPED: 2

2023-08-16 16:30 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9448](http://condorpiedra.andes.gob.ar:85/9448/mochawesome.html)
CYPRESS RUN: [8579](https://dashboard.cypress.io/projects/xr7gft/runs/8579/specs)
TEST START: 2023-08-16T16:29:46.832Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-08-16 18:10 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9453](http://condorpiedra.andes.gob.ar:85/9453/mochawesome.html)
CYPRESS RUN: [8583](https://dashboard.cypress.io/projects/xr7gft/runs/8583/specs)
TEST START: 2023-08-16T18:10:34.258Z
TOTAL: 353
SUCCESS: 349
FAIL: 2
SKIPPED: 2

2023-08-17 11:31 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9458](http://condorpiedra.andes.gob.ar:85/9458/mochawesome.html)
CYPRESS RUN: [8588](https://dashboard.cypress.io/projects/xr7gft/runs/8588/specs)
TEST START: 2023-08-17T11:31:01.380Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-17 11:59 UTC, MarianoCampetella requested changes

2023-08-17 11:59 UTC, MarianoCampetella commented on cypress/e2e/apps/rup/internacion/mapa-camas/detalle-cama.spec.ts
> +
Quitar los nuevos espacios y amendearlo.

2023-08-22 12:38 UTC, aldoEMatamala commented on cypress/e2e/apps/rup/internacion/mapa-camas/detalle-cama.spec.ts
> +
amendeado gracias!

2023-08-22 12:47 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9487](http://condorpiedra.andes.gob.ar:85/9487/mochawesome.html)
CYPRESS RUN: [8614](https://dashboard.cypress.io/projects/xr7gft/runs/8614/specs)
TEST START: 2023-08-22T12:46:44.882Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-22 13:16 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9489](http://condorpiedra.andes.gob.ar:85/9489/mochawesome.html)
CYPRESS RUN: [8616](https://dashboard.cypress.io/projects/xr7gft/runs/8616/specs)
TEST START: 2023-08-22T13:16:35.935Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-22 23:01 UTC, JuanIRamirez approved these changes
ok

2023-08-23 11:46 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9493](http://condorpiedra.andes.gob.ar:85/9493/mochawesome.html)
CYPRESS RUN: [8620](https://dashboard.cypress.io/projects/xr7gft/runs/8620/specs)
TEST START: 2023-08-23T11:46:09.848Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-23 12:05 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9494](http://condorpiedra.andes.gob.ar:85/9494/mochawesome.html)
CYPRESS RUN: [8621](https://dashboard.cypress.io/projects/xr7gft/runs/8621/specs)
TEST START: 2023-08-23T11:56:45.322Z
TOTAL: 360
SUCCESS: 349
FAIL: 9
SKIPPED: 2

2023-08-23 12:17 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9495](http://condorpiedra.andes.gob.ar:85/9495/mochawesome.html)
CYPRESS RUN: [8622](https://dashboard.cypress.io/projects/xr7gft/runs/8622/specs)
TEST START: 2023-08-23T12:16:55.944Z
TOTAL: 368
SUCCESS: 359
FAIL: 7
SKIPPED: 2

2023-08-24 11:14 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9498](http://condorpiedra.andes.gob.ar:85/9498/mochawesome.html)
CYPRESS RUN: [8625](https://dashboard.cypress.io/projects/xr7gft/runs/8625/specs)
TEST START: 2023-08-24T11:14:11.315Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-25 11:19 UTC, MarianoCampetella approved these changes

2023-08-29 13:48 UTC, merged