RUP - Implementa mockups en punto de inicio
andes/andes-test-integracion pull request #509
Opened 2024-01-22 17:22 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-370

### Funcionalidad desarrollada 

1.  Se corrigen test para adaptar la UI de la nueva implementación de RUP

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2024-01-22 17:55 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10321](http://condorpiedra.andes.gob.ar:85/10321/mochawesome.html)
CYPRESS RUN: [9428](https://dashboard.cypress.io/projects/xr7gft/runs/9428/specs)
TEST START: 2024-01-22T17:54:19.827Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-22 18:10 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10322](http://condorpiedra.andes.gob.ar:85/10322/mochawesome.html)
CYPRESS RUN: [9429](https://dashboard.cypress.io/projects/xr7gft/runs/9429/specs)
TEST START: 2024-01-22T18:09:22.877Z
TOTAL: 330
SUCCESS: 305
FAIL: 22
SKIPPED: 3

2024-01-23 12:53 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10327](http://condorpiedra.andes.gob.ar:85/10327/mochawesome.html)
CYPRESS RUN: [9434](https://dashboard.cypress.io/projects/xr7gft/runs/9434/specs)
TEST START: 2024-01-23T12:53:22.493Z
TOTAL: 389
SUCCESS: 375
FAIL: 11
SKIPPED: 3

2024-01-25 14:31 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10335](http://condorpiedra.andes.gob.ar:85/10335/mochawesome.html)
CYPRESS RUN: [9442](https://dashboard.cypress.io/projects/xr7gft/runs/9442/specs)
TEST START: 2024-01-25T14:31:16.721Z
TOTAL: 421
SUCCESS: 406
FAIL: 12
SKIPPED: 3

2024-01-25 17:44 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10338](http://condorpiedra.andes.gob.ar:85/10338/mochawesome.html)
CYPRESS RUN: [9445](https://dashboard.cypress.io/projects/xr7gft/runs/9445/specs)
TEST START: 2024-01-25T17:44:19.575Z
TOTAL: 393
SUCCESS: 391
FAIL: -1
SKIPPED: 3

2024-05-21 14:53 UTC, ma7payne commented
✅ TEST ok [(#10916)](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/10916/)

2024-06-07 17:33 UTC, MCele requested changes
Mati se ve hermosa la nueva pantalla :D 
Te comento por aca lo que estuvimos charlando que falta revisar:

- No se visualizan los fuera de agenda algunos dias (parece ser que es cuando no hay ninguna agenda para visualizar).
- Cuando se visualizan los fuera de agenda debería ser un sólo item para todos los fuera de agenda cargados en el día, en cambio ahora se visualiza uno por cada prestacion cargada.
![image](https://github.com/andes/andes-test-integracion/assets/19591224/63b7e359-5d97-4d2c-a0a9-6e717bd42002)

Dato de color aprovecharía a sacar el campo requerido en el selec de prestacion, ya que nunca se aplica como tal

2024-06-26 14:43 UTC, merged